<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container">
      <div class="row">

        <?= $error ? '<div class="col-12"><div class="alert alert-danger">'.$error.'</div></div>' : '' ?>

        <div class="col-12">
          <form method="POST" action="/login">
            <div class="form-group">
              <label for="user-name">Name</label>
              <input type="text" name="user_name" class="form-control" id="user-name" placeholder="User Name">
            </div>

            <div class="form-group">
              <label for="user-phone">Password</label>
              <input type="password" name="user_password" class="form-control" id="user-password" placeholder="User password">
            </div>

            <button type="submit" class="btn btn-primary">Login</button>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>
